Update github actions workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,9 @@
 name: Build, Test & Deploy
 
-on: [push, pull_request]
+on:
+  push:
+  pull_request:
+  workflow_dispatch:
 
 env:
   DOCKER_IMAGE_NAME: ghcr.io/fredagscafeen/web
@@ -10,12 +13,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v6
 
       - name: Setup python environment
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v6
         with:
           python-version: "3.8"
+          cache: "pip"
+          cache-dependency-path: |
+            requirements.txt
+            dev-requirements.txt
 
       - name: Setup pip version
         run: pip install pip==24.0.0
@@ -23,85 +30,118 @@ jobs:
       - name: Install python dependencies
         run: pip install -r requirements.txt -r dev-requirements.txt
 
-      - name: Cache pre-commit environments
-        uses: actions/cache@v3
-        with:
-          path: ~/.cache/pre-commit
-          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-pre-commit-
-
       - name: Run pre-commit checks
-        uses: pre-commit/action@v3.0.0
+        uses: pre-commit/action@v3
 
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v6
 
-      - name: Pull existing images
-        run: docker compose pull
-
-      - name: Restore docker layer cache
-        uses: satackey/action-docker-layer-caching@v0.0.11
-        continue-on-error: true
-
-      - name: Build image
-        run: ./build
-
-      - name: Save docker image
-        run: docker save "$DOCKER_IMAGE_NAME" | gzip > image.tar.gz
-
-      - name: Upload docker image for other jobs
-        uses: actions/upload-artifact@v4
+      - name: Login to ghcr.io
+        uses: docker/login-action@v4
         with:
-          name: image
-          path: image.tar.gz
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Docker metadata
+        id: meta
+        uses: docker/metadata-action@v6
+        with:
+          images: |
+            ${{ env.DOCKER_IMAGE_NAME }}
+          labels: |
+            org.opencontainers.image.title=Fredagscafeen Web
+            org.opencontainers.image.description=Web application for Fredagscafeen
+            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
+            org.opencontainers.image.url=https://fredagscafeen.dk
+            org.opencontainers.image.vendor=Fredagscafeen
+          tags: |
+            type=raw,value={{sha}}
+
+      - name: Short SHA
+        id: short_sha
+        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v4
+
+      - name: Build Docker image
+        uses: docker/build-push-action@v7
+        with:
+          context: .
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          outputs: type=docker,dest=${{ runner.temp }}/web-docker-image.tar
+          build-args: |
+            GIT_COMMIT_HASH=${{ steps.short_sha.outputs.SHORT_SHA }}
+            GIT_BRANCH=${{ github.ref_name }}
+
+      - name: Upload image for other jobs
+        uses: actions/upload-artifact@v7
+        with:
+          name: web-docker-image
+          path: ${{ runner.temp }}/web-docker-image.tar
+
+    outputs:
+      image_tag: ${{ steps.meta.outputs.version }}
 
   test:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Download docker image
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v7
         with:
-          name: image
+          name: web-docker-image
+          path: ${{ runner.temp }}/web-docker-image.tar
 
       - name: Load docker image
-        run: docker load < image.tar.gz
+        run: docker load --input ${{ runner.temp }}/web-docker-image.tar
 
       - name: Run tests
-        run: docker run --env DJANGO_SETTINGS_MODULE=fredagscafeen.settings.local "$DOCKER_IMAGE_NAME" ./manage.py test
-
-  test-docker-compose:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Download docker image
-        uses: actions/download-artifact@v4
-        with:
-          name: image
-
-      - name: Load docker image
-        run: docker load < image.tar.gz
-
-      - name: Test docker compose
         run: |
-          for k in "SECRET_KEY" "RECAPTCHA_PUBLIC_KEY" "RECAPTCHA_PRIVATE_KEY"; do
-            echo "$k=foo" >> ".env"
-          done
-          docker network create traefik
-          docker compose up -d
-          sleep 10
-          res=$(docker compose ps)
-          echo "$res"
-          if echo "$res" | grep Exit &>/dev/null; then
-            exit 1
-          fi
+          docker run --env DJANGO_SETTINGS_MODULE=fredagscafeen.settings.local \
+          "${{ env.DOCKER_IMAGE_NAME }}:${{ needs.build.outputs.image_tag }}" \
+          ./manage.py test
+
+  # test-docker-compose:
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v6
+  #       with:
+  #         sparse-checkout: |
+  #           docker-compose.yml
+
+  #     - name: Download docker image
+  #       uses: actions/download-artifact@v7
+  #       with:
+  #         name: web-docker-image
+  #         path: ${{ runner.temp }}/web-docker-image.tar
+
+  #     - name: Load docker image
+  #       run: docker load --input ${{ runner.temp }}/web-docker-image.tar
+
+  #     - name: Test docker compose
+  #       run: |
+  #         for k in "SECRET_KEY" "RECAPTCHA_PUBLIC_KEY" "RECAPTCHA_PRIVATE_KEY"; do
+  #           echo "$k=foo" >> ".env"
+  #         done
+  #         docker network create traefik
+  #         docker compose up -d
+  #         sleep 10
+  #         res=$(docker compose ps)
+  #         echo "$res"
+  #         if echo "$res" | grep Exit &>/dev/null; then
+  #           exit 1
+  #         fi
 
   release:
     runs-on: ubuntu-latest
@@ -110,26 +150,36 @@ jobs:
       - pre-commit
       - build
       - test
-      - test-docker-compose
     steps:
       - name: Download docker image
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v7
         with:
-          name: image
+          name: web-docker-image
+          path: ${{ runner.temp }}/web-docker-image.tar
 
       - name: Load docker image
-        run: docker load < image.tar.gz
+        run: docker load --input ${{ runner.temp }}/web-docker-image.tar
 
-      - name: Publish image to ghcr.io
+      - name: Login to ghcr.io
+        uses: docker/login-action@v4
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Tag image with latest
+        run: docker tag "${{ env.DOCKER_IMAGE_NAME }}:${{ needs.build.outputs.image_tag }}" "${{ env.DOCKER_IMAGE_NAME }}:latest"
+
+      - name: Push Docker image
         run: |
-          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username "${{ github.actor }}" --password-stdin
-          docker push "$DOCKER_IMAGE_NAME"
+          docker push "${{ env.DOCKER_IMAGE_NAME }}:${{ needs.build.outputs.image_tag }}"
+          docker push "${{ env.DOCKER_IMAGE_NAME }}:latest"
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: release
-    steps:
-      - name: Deploy image to production
-        run: curl --fail -X POST "$WEBHOOK_URL"
-        env:
-          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
+  # deploy: THIS IS BROKEN AND SHOULD NOT BE USED UNTIL FIXED - WEBHOOK POINTS TO webhooks.tyilo.com/hook
+  #   runs-on: ubuntu-latest
+  #   needs: release
+  #   steps:
+  #     - name: Deploy image to production
+  #       run: curl --fail -X POST "$WEBHOOK_URL"
+  #       env:
+  #         WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
